#!/usr/bin/env python3
"""assemble-master-xlsx.py — concat per-module xlsx into one master workbook.

Reads a manifest (JSON) describing the section ordering and source files,
copies each source's sheets into a master workbook with prefixed sheet
names, and adds a README/index sheet.

Usage:
    python3 assemble-master-xlsx.py \\
        --manifest scripts/artifact-generators/assemblers/master-workbook.manifest.json \\
        --output .planning/runs/self-application/portfolio/c1v-self-application.xlsx

Sheet-name prefix convention: "{tag}_{original_name}" — e.g. M7's
"Founder Web UI" sheet from interface_matrix.xlsx becomes
"M7_IF_Founder Web UI". Sheet names truncated to 31 chars (Excel limit).
"""
from __future__ import annotations

import argparse
import json
import re
from copy import copy
from pathlib import Path
from typing import Any, Dict, List

from openpyxl import Workbook, load_workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.worksheet import Worksheet


SHEET_NAME_MAX = 31  # Excel hard limit
INVALID_SHEET_CHARS = re.compile(r'[\\/?*\[\]:]')


def _sanitize_sheet_name(name: str) -> str:
    cleaned = INVALID_SHEET_CHARS.sub('_', name).strip()
    if len(cleaned) > SHEET_NAME_MAX:
        cleaned = cleaned[:SHEET_NAME_MAX - 3] + '...'
    return cleaned or 'Sheet'


def _unique_sheet_name(wb: Workbook, base: str) -> str:
    name = _sanitize_sheet_name(base)
    if name not in wb.sheetnames:
        return name
    # Append numeric suffix until unique.
    for i in range(2, 100):
        candidate = _sanitize_sheet_name(f"{base}_{i}")
        if candidate not in wb.sheetnames:
            return candidate
    raise RuntimeError(f"could not find unique sheet name for {base}")


def _copy_sheet(src_ws: Worksheet, dst_wb: Workbook, dst_name: str) -> Worksheet:
    """Copy values, formats, column widths, and merged cells into a new sheet."""
    dst_ws = dst_wb.create_sheet(title=dst_name)

    # Cell values + styles.
    for row in src_ws.iter_rows():
        for cell in row:
            new_cell = dst_ws.cell(
                row=cell.row, column=cell.column, value=cell.value
            )
            if cell.has_style:
                new_cell.font = copy(cell.font)
                new_cell.fill = copy(cell.fill)
                new_cell.border = copy(cell.border)
                new_cell.alignment = copy(cell.alignment)
                new_cell.number_format = cell.number_format
                new_cell.protection = copy(cell.protection)

    # Column widths.
    for letter, dim in src_ws.column_dimensions.items():
        if dim.width:
            dst_ws.column_dimensions[letter].width = dim.width

    # Row heights.
    for idx, dim in src_ws.row_dimensions.items():
        if dim.height:
            dst_ws.row_dimensions[idx].height = dim.height

    # Merged cells.
    for rng in src_ws.merged_cells.ranges:
        dst_ws.merge_cells(str(rng))

    # Sheet view (frozen panes etc).
    if src_ws.freeze_panes:
        dst_ws.freeze_panes = src_ws.freeze_panes

    return dst_ws


def _add_index_sheet(wb: Workbook, manifest: Dict[str, Any], copied: List[Dict[str, Any]]) -> None:
    ws = wb.create_sheet(title='00_README', index=0)
    title = manifest.get('title', 'Master Workbook')
    subtitle = manifest.get('subtitle', '')

    # Title.
    ws['A1'] = title
    ws['A1'].font = Font(bold=True, size=18)
    ws.merge_cells('A1:E1')
    if subtitle:
        ws['A2'] = subtitle
        ws['A2'].font = Font(italic=True, size=12, color='555555')
        ws.merge_cells('A2:E2')

    ws['A4'] = 'Section'
    ws['B4'] = 'Source File'
    ws['C4'] = 'Sheets In Master'
    ws['D4'] = 'Status'
    for col in 'ABCD':
        c = ws[f'{col}4']
        c.font = Font(bold=True)
        c.fill = PatternFill('solid', fgColor='DDDDDD')

    row = 5
    for entry in copied:
        ws.cell(row=row, column=1, value=entry['section'])
        ws.cell(row=row, column=2, value=entry['source'])
        ws.cell(row=row, column=3, value=', '.join(entry['sheets']))
        ws.cell(row=row, column=4, value=entry['status'])
        row += 1

    # Column widths.
    ws.column_dimensions['A'].width = 32
    ws.column_dimensions['B'].width = 60
    ws.column_dimensions['C'].width = 50
    ws.column_dimensions['D'].width = 12

    # Provenance footer.
    row += 2
    ws.cell(row=row, column=1, value='Generated by').font = Font(italic=True)
    ws.cell(row=row, column=2,
            value='scripts/artifact-generators/assemblers/assemble-master-xlsx.py')


def assemble(manifest_path: Path, output_path: Path) -> Dict[str, Any]:
    manifest = json.loads(manifest_path.read_text(encoding='utf-8'))
    sections = manifest.get('sections', [])

    wb = Workbook()
    # Remove the default 'Sheet' that gets created; we'll add our own first.
    default = wb.active
    wb.remove(default)

    copied_log: List[Dict[str, Any]] = []
    total_sheets = 0

    for section in sections:
        tag = section.get('tag', section.get('name', 'X'))
        sources = section.get('sources', [])
        for src in sources:
            src_path = Path(src).resolve()
            entry: Dict[str, Any] = {
                'section': section.get('name', tag),
                'source': str(src_path),
                'sheets': [],
                'status': 'ok',
            }
            if not src_path.exists():
                entry['status'] = 'missing'
                copied_log.append(entry)
                continue
            try:
                src_wb = load_workbook(str(src_path), data_only=False)
                for sheetname in src_wb.sheetnames:
                    src_ws = src_wb[sheetname]
                    target = _unique_sheet_name(wb, f"{tag}_{sheetname}")
                    _copy_sheet(src_ws, wb, target)
                    entry['sheets'].append(target)
                    total_sheets += 1
            except Exception as exc:
                entry['status'] = f"error: {type(exc).__name__}: {exc}"
            copied_log.append(entry)

    # Insert README index sheet at position 0.
    _add_index_sheet(wb, manifest, copied_log)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(str(output_path))

    return {
        'output': str(output_path),
        'total_sheets': total_sheets + 1,  # + README
        'sources_processed': len(copied_log),
        'log': copied_log,
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--manifest', required=True)
    ap.add_argument('--output', required=True)
    args = ap.parse_args()

    result = assemble(Path(args.manifest), Path(args.output))
    print(json.dumps(result, indent=2))


if __name__ == '__main__':
    main()
